name: Atualizar vídeos do YouTube

on:
  schedule:
    # Seg a Sex: 7h30 BRT (10h30 UTC) e 19h30 BRT (22h30 UTC)
    - cron: '10 10 * * 1-5' # Segunda a Sexta, 10h30 UTC
    - cron: '30 22 * * 1-5' # Segunda a Sexta, 22h30 UTC

    # Sábado e Domingo: 9h BRT (12h UTC) e 19h BRT (22h UTC)
    - cron: '0 12 * * 0,6'  # Domingo e Sábado, 12h UTC
    - cron: '0 22 * * 0,6'  # Domingo e Sábado, 22h UTC

    # Cron pós-live para garantir atualização rápida do status "ao vivo"
    - cron: '0 2 * * 1' # Segunda-feira 02:00 UTC (Domingo 23h BRT)
    - cron: '0 2 * * 5' # Sexta-feira 02:00 UTC (Quinta 23h BRT)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: pip install requests

    - name: Executar script
      run: python api/youtube_fetch.py
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    - name: Commit e push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add youtube.json
        git commit -m "Atualiza vídeos do YouTube automaticamente" || echo "Nenhuma alteração para commit"
        git push