name: Atualizar vídeos do YouTube

on:
  schedule:
    #Café com fé manhã
    # SEG a SEX: 07:00 BRT → 10:00 UTC
    - cron: '0 10 * * 1-5'
    # SÁB e DOM: 09:20 BRT → 12:00 UTC
    - cron: '20 12 * * 6,0'

    # Pré-LIVE:
    # SÁB e DOM: 18:50 BRT → 21:50 UTC
    - cron: '50 21 * * 6,0'
    # SÁB e DOM: 19:35 BRT → 22:35 UTC
    - cron: '35 22 * * 6,0'

    # Pós-live:
    # QUINTA 21:15 BRT → sexta 00:15 UTC
    - cron: '15 0 * * 5'
    # SEXTA 22:00 BRT → sábado 01:00 UTC
    - cron: '0 1 * * 6'
    # SÁBADO 22:00 BRT → domingo 01:00 UTC
    - cron: '0 1 * * 0'
    # DOMINGO 21:40 BRT → segunda 00:40 UTC
    - cron: '40 0 * * 1'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: pip install requests

    - name: Executar script
      run: python api/youtube_fetch.py
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    - name: Commit e push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add youtube.json
        git commit -m "Atualiza vídeos do YouTube automaticamente" || echo "Nenhuma alteração para commit"
        git push